########
# java #
########
[[plugins]]
repo = 'uiiaoo/java-syntax.vim'
on_ft = ['java']

##########
# python #
##########
[[plugins]]
repo = 'vim-python/python-syntax'
hook_add = 'let g:python_highlight_all = 1'
on_ft = ['py', 'python']
 
######
# es #
######
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts', 'tsx', 'jsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
hook_add = 'au BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact'
on_ft = ['ts', 'tsx', 'jsx']

#######
# c++ #
#######
[[plugins]]
repo = 'bfrg/vim-cpp-modern'
hook_add = '''

let g:cpp_attributes_highlight = 1
let g:cpp_member_highlight = 1
let g:cpp_simple_highlight = 1

'''
on_ft = ['cpp', 'c', 'hpp', 'h']

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['cpp', 'c', 'hpp', 'h']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
hook_add = '''
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1

let g:cpp_concepts_highlight = 1
'''
on_ft = ['cpp', 'c', 'hpp', 'h']

########
# rust #
########
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''

let g:rustfmt_autosave = 1

'''
on_ft = ['rs']

###########
# Haskell #
###########
[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['hs', 'hls']

[[plugins]]
repo = 'vimwiki/vimwiki'
on_ft = ['wiki']

